### ISSUE TITLE
TCL support for yowasp-yosys

### ISSUE THREAD

**Issue by kammoh** [YoWASP/yosys#20]
Would it be possible to add TCL support to `yowasp-yosys`?

**Comment by whitequark** [comment]
Quite possibly; I would have to look closer at build requirements of Tcl to answer for sure.

**Comment by kammoh** [comment]
That would be really great! Thanks!

**Comment by whitequark** [comment]
I've tried to build Tcl for WASI. Unfortunately, in spite of its reputation for portability, Tcl has a large amount of dependencies on Unix-specific APIs (especially socket ones are problematic, though there are many more than that), and getting it to build and run under WASI is a significant undertaking. There is no way I can see to build Tcl with the OS APIs disabled.

I will not be porting Tcl to WASI, but if someone else does this, I will consider shipping a third-party port as a part of YoWASP.
