### ISSUE TITLE
Support for Mac M1

### ISSUE THREAD

**Issue by hossein1387** [YoWASP/yosys#23]
I am able to install `yowasp` using: `python -m pip install yowasp-yosys` but when I try to run it I get:

`RuntimeError: unsupported architecture for wasmtime: arm64`

Any plan to support arm64 for Mac M1?

**Comment by whitequark** [comment]
This would require ARM64 Mac support in the backend we use, [wasmtime](https://github.com/bytecodealliance/wasmtime). Currently it only supports ARM64 Linux, but feel free to open an issue upstream!

**Comment by hossein1387** [comment]
will do, thanks!

**Comment by hossein1387** [comment]
Following the link you sent, I found that most of the works is already done: https://github.com/bytecodealliance/wasmtime-go/issues/53. However, for stable a release, they need a CI and Github actions currently does not support [VMs for Mac M1](https://github.com/actions/virtual-environments/issues/2187).
