### ISSUE TITLE
binding to pyosys

### ISSUE THREAD

**Issue by proppy** [YoWASP/yosys#25]
it would be nice to have https://github.com/YoWASP/yosys/blob/develop/pypi/yowasp_yosys/__init__.py exposes the same API as pyosys  (https://github.com/YosysHQ/yosys/pull/905), is that something that has already been looked at?

**Comment by whitequark** [comment]
See #8.

**Comment by proppy** [comment]
@whitequark oh sorry for the duplicate, I'll comment on the original issue.
